### ISSUE TITLE
Change hex color in css

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/datasnakes.github.io#2]
Change `#fed136` in agency.min.css to `#99e166`

### How to contribute
1. Fork our repo
2. Check out the `dev-master` branch
3. Create your own branch from the `dev-master` branch
4. Add and test your updates.
5. Submit a PR that adds the updates to the `dev-master` branch

**Comment by frankles12** [comment]
On it!

**Comment by sdhutchins** [comment]
Addressed by #3 

Thank you, @frankles12
